#!/usr/bin/env bash
#
# ติดตั้งชุด AI กลาง (ai/) ให้ Claude Code, Codex CLI และ Antigravity CLI ใช้ร่วมกันทุก project
#
#   ./install.sh              เลือกจากเมนูว่าจะติดตั้งตัวไหน (จำค่าที่เลือกไว้รอบหน้า)
#   ./install.sh all          ติดตั้งทุกตัว ไม่ถามเมนู
#   ./install.sh claude       ติดตั้งเฉพาะที่ระบุ (claude | codex | antigravity | shell)
#   ./install.sh --status     ดูว่าติดตั้งอะไรไว้บ้าง
#   ./install.sh --uninstall  ถอนเฉพาะสิ่งที่ script นี้สร้าง
#
# env: AI_AGENT_NO_SHELL=1  ข้ามการแก้ shell rc
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="$ROOT/ai"
STAMP="$(date +%Y%m%d-%H%M%S)"

CLAUDE_HOME="${CLAUDE_HOME:-$HOME/.claude}"
CODEX_HOME="${CODEX_HOME:-$HOME/.codex}"
# Antigravity CLI (agy) — customization root ระดับ global
AGY_HOME="${AGY_HOME:-$HOME/.gemini/config}"
AI_HOME="${AI_HOME:-$HOME/.ai}"

PREFS="$ROOT/.install-prefs"

MARKER="# >>> ai-agent sync >>>"
MARKER_END="# <<< ai-agent sync <<<"

info()  { printf '  %s\n' "$*"; }
head2() { printf '\n\033[1m%s\033[0m\n' "$*"; }
warn()  { printf '  \033[33m!\033[0m %s\n' "$*"; }
ok()    { printf '  \033[32m✓\033[0m %s\n' "$*"; }
count() { ls -1 "$@" 2>/dev/null | wc -l | tr -d ' '; }
count_dir() { ls -1 "$1" 2>/dev/null | wc -l | tr -d ' '; }

# ย้ายไฟล์จริง (ที่ไม่ใช่ symlink ของเรา) ไปเป็น .bak ก่อนเขียนทับ
backup_if_real() {
  local target="$1"
  [ -e "$target" ] || [ -L "$target" ] || return 0
  if [ -L "$target" ]; then
    case "$(readlink "$target")" in
      "$SRC"|"$SRC"/*|"$AI_HOME"|"$AI_HOME"/*) return 0 ;;   # link ของเราเอง — เขียนทับได้เลย
    esac
  fi
  mv "$target" "$target.bak-$STAMP"
  warn "สำรองของเดิม → $(basename "$target").bak-$STAMP"
}

link() {
  local src="$1" dst="$2"
  backup_if_real "$dst"
  mkdir -p "$(dirname "$dst")"
  ln -sfn "$src" "$dst"
}

# copy ไฟล์จริง — ใช้กับ runtime ที่ไม่ follow symlink (Codex)
# แปลง command markdown → SKILL.md (ใช้ได้ทั้ง Codex และ Antigravity)
md_to_skill() {
  local src="$1" dst="$2" name="$3"
  mkdir -p "$(dirname "$dst")"
  python3 - "$src" "$dst" "$name" <<'SKILLPY'
import re, sys, pathlib

src, dst, name = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2]), sys.argv[3]
raw = src.read_text(encoding="utf-8")

description = ""
match = re.match(r"^---\r?\n(.*?)\r?\n---\r?\n?", raw, re.S)
if match:
    for line in match.group(1).splitlines():
        key, _, value = line.partition(":")
        if key.strip() == "description":
            description = value.strip().strip("'\"")
    body = raw[match.end():]
else:
    body = raw

# Codex ส่งข้อความที่ user พิมพ์ต่อท้าย $<name> เข้ามาเป็น input
body = body.replace("$ARGUMENTS", f"ข้อความที่ user พิมพ์ต่อท้าย `${name}`")

def quote(text):
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'

dst.write_text(
    "---\n"
    f"name: {name}\n"
    f"description: {quote(description)}\n"
    "---\n\n"
    f"<!-- generated by ai-agent install.sh from ai/commands/{src.name} - DO NOT EDIT -->\n\n"
    "> อ่าน `~/.ai/AI.md` (rule กลาง) ก่อนเริ่ม ถ้ายังไม่ได้อ่านใน session นี้\n\n"
    + body.strip() + "\n",
    encoding="utf-8",
)
SKILLPY
}

link_dir_contents() {
  local src_dir="$1" dst_dir="$2" ext="$3"
  local file
  for file in "$src_dir"/*"$ext"; do
    [ -e "$file" ] || continue
    link "$file" "$dst_dir/$(basename "$file")"
  done
}

detect_rc() {
  case "${SHELL##*/}" in
    zsh)  printf '%s\n' "$HOME/.zshrc" ;;
    bash) if [ -f "$HOME/.bash_profile" ]; then printf '%s\n' "$HOME/.bash_profile"; else printf '%s\n' "$HOME/.bashrc"; fi ;;
    *)    printf '%s\n' "" ;;
  esac
}

# ลบ block เดิมของเราออกจาก shell rc (กัน path เก่าค้างเวลาย้ายโฟลเดอร์)
strip_shell_block() {
  local rc="$1" tmp
  [ -f "$rc" ] || return 0
  grep -q 'ai-agent.*sync >>>' "$rc" || return 0
  tmp="$(mktemp)"
  # match ทุก marker ของ ai-agent ไม่ผูกกับชื่อรุ่นใดรุ่นหนึ่ง — กัน block ค้างตอนเปลี่ยนชื่อ
  awk '
    /^# >>> ai-agent.* sync >>>$/ { skip = 1 }
    !skip                         { print }
    /^# <<< ai-agent.* sync <<<$/ { skip = 0 }
  ' "$rc" > "$tmp"
  mv "$tmp" "$rc"
}

install_shared() {
  head2 "Shared source"
  link "$SRC" "$AI_HOME"
  ok "$AI_HOME → $SRC"
  info "commands และ agents อ้างถึง ~/.ai/ ได้จากทุก assistant"

  # features.md เป็นไฟล์ generate ทั้งไฟล์ — ให้ .gitattributes (merge=ours) ทำงานได้
  # ไม่ต้อง resolve conflict มือ แค่รัน /reindex ใหม่
  if command -v git >/dev/null 2>&1; then
    if [ "$(git config --global --get merge.ours.driver 2>/dev/null)" != "true" ]; then
      git config --global merge.ours.driver true
      ok "git merge driver 'ours' — features.md จะไม่ merge conflict"
    fi
  fi
}

install_claude() {
  head2 "Claude Code"
  link "$SRC/AI.md" "$CLAUDE_HOME/CLAUDE.md"
  ok "$CLAUDE_HOME/CLAUDE.md"
  link_dir_contents "$SRC/commands" "$CLAUDE_HOME/commands" .md
  ok "$CLAUDE_HOME/commands/ ($(count "$SRC"/commands/*.md) commands)"
  link_dir_contents "$SRC/agents" "$CLAUDE_HOME/agents" .md
  ok "$CLAUDE_HOME/agents/ ($(count "$SRC"/agents/*.md) agents)"
}

# Codex 0.155+ เลิกใช้ ~/.codex/prompts แล้ว — custom command ต้องเป็น skill
# (~/.codex/skills/<name>/SKILL.md) และ frontmatter รับแค่
# name, description, license, allowed-tools, metadata
install_codex() {
  head2 "Codex CLI"
  # AGENTS.md เป็นไฟล์เดี่ยว Codex อ่านผ่าน symlink ได้ปกติ
  link "$SRC/AI.md" "$CODEX_HOME/AGENTS.md"
  ok "$CODEX_HOME/AGENTS.md"

  local file name backed_up=0
  for file in "$SRC"/commands/*.md; do
    name="$(basename "$file" .md)"
    local dest="$CODEX_HOME/skills/$name"
    # skill เดิมที่ไม่ใช่ของเรา → ย้ายไป backup ก่อน ไม่ลบทิ้ง
    if [ -d "$dest" ] && ! grep -q 'generated by ai-agent' "$dest/SKILL.md" 2>/dev/null; then
      mkdir -p "$CODEX_HOME/skills-disabled-old-template"
      mv "$dest" "$CODEX_HOME/skills-disabled-old-template/$name.bak-$STAMP"
      backed_up=$((backed_up + 1))
    fi
    md_to_skill "$file" "$dest/SKILL.md" "$name"
  done
  [ "$backed_up" -gt 0 ] && warn "ย้าย skill เดิม $backed_up ตัวไป $CODEX_HOME/skills-disabled-old-template/"
  ok "$CODEX_HOME/skills/ ($(count "$SRC"/commands/*.md) skills)"

  # prompts ของเก่า (Codex รุ่นเก่า) — เก็บกวาดเฉพาะที่เราสร้างเอง
  for file in "$CODEX_HOME"/prompts/*.md; do
    [ -e "$file" ] || [ -L "$file" ] || continue
    if [ -L "$file" ] || grep -q 'generated by ai-agent' "$file" 2>/dev/null; then
      rm -f "$file"
    fi
  done
  rmdir "$CODEX_HOME/prompts" 2>/dev/null || true

  info "เรียกด้วย \$<name> เช่น \$spec — Codex ใช้ \$ ไม่ใช่ /"
  info "Codex ไม่มี subagent — skill จะอ่าน ~/.ai/agents/*.md แล้วทำเองใน pass เดียว"
}

# Antigravity CLI (agy) ใช้ skill เหมือน Codex — workflows/*.md เป็นของเก่าที่กำลังถูก migrate
# memory: rules เป็น directory-based (GEMINI.md/AGENTS.md ใน repo) ไม่มี global file
#         → skill แต่ละตัวถูก generate ให้อ่าน ~/.ai/AI.md เองตอนเริ่ม
install_antigravity() {
  head2 "Antigravity CLI (agy)"
  local file name backed_up=0 dest
  for file in "$SRC"/commands/*.md; do
    name="$(basename "$file" .md)"
    dest="$AGY_HOME/skills/$name"
    if [ -d "$dest" ] && ! grep -q 'generated by ai-agent' "$dest/SKILL.md" 2>/dev/null; then
      mkdir -p "$AGY_HOME/skills-disabled-old"
      mv "$dest" "$AGY_HOME/skills-disabled-old/$name.bak-$STAMP"
      backed_up=$((backed_up + 1))
    fi
    md_to_skill "$file" "$dest/SKILL.md" "$name"
  done
  [ "$backed_up" -gt 0 ] && warn "ย้าย skill เดิม $backed_up ตัวไป $AGY_HOME/skills-disabled-old/"
  ok "$AGY_HOME/skills/ ($(count "$SRC"/commands/*.md) skills)"
  info "เรียกด้วยชื่อ skill ได้เลย เช่น \"ใช้ skill spec ...\" หรือ /skills ดูรายการ"

  command -v agy >/dev/null 2>&1 || warn "ไม่พบ binary 'agy' ใน PATH — ตรวจว่า ~/.local/bin อยู่ใน PATH หรือยัง"
}

install_shell() {
  head2 "Shell wrapper (Codex + Antigravity auto-sync)"
  if [ -n "${AI_AGENT_NO_SHELL:-}" ]; then
    info "ข้าม — AI_AGENT_NO_SHELL ถูกตั้งไว้"
    return 0
  fi

  local rc
  rc="$(detect_rc)"
  if [ -z "$rc" ]; then
    warn "ไม่รู้จัก shell '${SHELL##*/}' — ข้าม (เพิ่ม wrapper เองได้ ดู README)"
    return 0
  fi

  strip_shell_block "$rc"
  {
    printf '\n%s\n' "$MARKER"
    printf '%s\n' "# sync skill ก่อนเปิดทุกครั้ง (Claude ใช้ symlink ไม่ต้อง sync)"
    printf '%s\n' "#   codex / agy - command ถูก generate เป็น SKILL.md ไม่ใช่ symlink"
    printf '%s\n' "codex() {"
    printf '%s\n' "  [ -x \"$ROOT/install.sh\" ] && AI_AGENT_NO_SHELL=1 \"$ROOT/install.sh\" codex >/dev/null 2>&1"
    printf '%s\n' "  command codex \"\$@\""
    printf '%s\n' "}"
    printf '%s\n' "agy() {"
    printf '%s\n' "  [ -x \"$ROOT/install.sh\" ] && AI_AGENT_NO_SHELL=1 \"$ROOT/install.sh\" antigravity >/dev/null 2>&1"
    printf '%s\n' "  command agy \"\$@\""
    printf '%s\n' "}"
    printf '%s\n' "$MARKER_END"
  } >> "$rc"

  ok "$rc — ตั้ง codex() + agy() wrapper ชี้ไป $ROOT"
  info "เปิด terminal ใหม่ หรือ: source $rc"
}

uninstall() {
  head2 "Uninstall"
  local removed=0 path
  for path in "$AI_HOME" \
              "$CLAUDE_HOME/CLAUDE.md" "$CODEX_HOME/AGENTS.md" \
              "$CLAUDE_HOME"/commands/*.md "$CLAUDE_HOME"/agents/*.md; do
    [ -L "$path" ] || continue
    case "$(readlink "$path")" in
      "$SRC"|"$SRC"/*|"$AI_HOME"/*) rm -f "$path"; info "ลบ $path"; removed=$((removed + 1)) ;;
    esac
  done
  for path in "$AGY_HOME"/skills/*/SKILL.md "$CODEX_HOME"/skills/*/SKILL.md; do
    [ -f "$path" ] || continue
    if grep -q 'generated by ai-agent' "$path"; then
      rm -rf "$(dirname "$path")"; info "ลบ $(dirname "$path")"; removed=$((removed + 1))
    fi
  done
  local backup
  for backup in "$CODEX_HOME/skills-disabled-old-template" "$AGY_HOME/skills-disabled-old"; do
    [ -d "$backup" ] && warn "skill เดิมอยู่ที่ $backup/ — กู้เองได้ด้วย mv"
  done
  local rc
  rc="$(detect_rc)"
  if [ -n "$rc" ] && [ -f "$rc" ] && grep -qF "$MARKER" "$rc"; then
    strip_shell_block "$rc"
    info "ลบ codex()/agy() wrapper จาก $rc"
    removed=$((removed + 1))
  fi
  ok "ลบไปทั้งหมด $removed รายการ (ไฟล์ .bak-* ยังอยู่ ถ้าต้องการกู้คืน)"
}

status() {
  head2 "Status"
  local path dir rc
  for path in "$AI_HOME" "$CLAUDE_HOME/CLAUDE.md" "$CODEX_HOME/AGENTS.md"; do
    if [ -L "$path" ]; then ok "$path → $(readlink "$path")"; else warn "$path ยังไม่ได้ติดตั้ง"; fi
  done
  for dir in "$CLAUDE_HOME/commands" "$CLAUDE_HOME/agents" "$CODEX_HOME/skills" "$AGY_HOME/skills"; do
    [ -d "$dir" ] && info "$dir — $(count_dir "$dir") รายการ"
  done
  rc="$(detect_rc)"
  if [ -n "$rc" ] && [ -f "$rc" ] && grep -qF "$MARKER" "$rc"; then
    ok "$rc — มี codex()/agy() wrapper"
  else
    warn "ยังไม่มี codex()/agy() wrapper (รัน: $0 shell)"
  fi
}

# ---------- เมนูเลือก assistant ----------

SEL_CLAUDE=1 SEL_CODEX=1 SEL_AGY=1 SEL_SHELL=1

# ค่า default: ติ๊กเฉพาะตัวที่มี binary จริงในเครื่อง
detect_defaults() {
  command -v claude >/dev/null 2>&1 && SEL_CLAUDE=1 || SEL_CLAUDE=0
  command -v codex  >/dev/null 2>&1 && SEL_CODEX=1  || SEL_CODEX=0
  command -v agy    >/dev/null 2>&1 && SEL_AGY=1    || SEL_AGY=0
  # shell wrapper จำเป็นเฉพาะตัวที่ต้อง generate ไฟล์
  if [ "$SEL_CODEX" = 1 ] || [ "$SEL_AGY" = 1 ]; then SEL_SHELL=1; else SEL_SHELL=0; fi
}

load_prefs() {
  [ -f "$PREFS" ] || return 1
  # shellcheck disable=SC1090
  . "$PREFS"
  return 0
}

save_prefs() {
  cat > "$PREFS" <<PREFSEOF
# ตัวเลือกล่าสุดของ ./install.sh — ลบไฟล์นี้เพื่อกลับไปใช้ค่า auto-detect
SEL_CLAUDE=$SEL_CLAUDE
SEL_CODEX=$SEL_CODEX
SEL_AGY=$SEL_AGY
SEL_SHELL=$SEL_SHELL
PREFSEOF
}

LABELS=("Claude Code" "Codex CLI" "Antigravity CLI" "Shell wrapper")
SEL=(1 1 1 1)
CURSOR=0
MENU_LINES=0
STTY_SAVED=""

hint_for() {
  case "$1" in
    0) binary_hint claude ;;
    1) binary_hint codex ;;
    2) binary_hint agy ;;
    3) printf 'auto-sync ตอนเปิด codex/agy' ;;
  esac
}

binary_hint() {
  if command -v "$1" >/dev/null 2>&1; then
    printf 'พบ %s' "$1"
  else
    printf 'ไม่พบ %s ในเครื่อง' "$1"
  fi
}

# ย้ายค่าระหว่างตัวแปร SEL_* กับ array ที่เมนูใช้
sel_to_array() { SEL=("$SEL_CLAUDE" "$SEL_CODEX" "$SEL_AGY" "$SEL_SHELL"); }
array_to_sel() {
  SEL_CLAUDE="${SEL[0]}"; SEL_CODEX="${SEL[1]}"
  SEL_AGY="${SEL[2]}";    SEL_SHELL="${SEL[3]}"
}

restore_term() {
  printf '\033[?25h'                                  # โชว์ cursor กลับ
  [ -n "$STTY_SAVED" ] && stty "$STTY_SAVED" 2>/dev/null || true
}

draw_menu() {
  printf '\n\033[1m  เลือก assistant ที่จะติดตั้ง\033[0m\n\n'
  local i pointer box label_style
  for i in "${!LABELS[@]}"; do
    if [ "$i" = "$CURSOR" ]; then pointer=$'\033[36m❯\033[0m'; label_style=$'\033[1m'
    else                          pointer=' ';                   label_style=''
    fi
    if [ "${SEL[$i]}" = 1 ]; then box=$'\033[32m◉\033[0m'
    else                          box='◯'
    fi
    printf '  %b %b %b%-18s\033[0m \033[2m%s\033[0m\n' \
      "$pointer" "$box" "$label_style" "${LABELS[$i]}" "$(hint_for "$i")"
  done
  printf '\n  \033[2m↑/↓ เลื่อน · space ติ๊ก · a ทั้งหมด · n ล้าง · enter ยืนยัน · q ออก\033[0m\n'
  MENU_LINES=$((3 + ${#LABELS[@]} + 2))
}

redraw_menu() {
  printf '\033[%dA\033[J' "$MENU_LINES"
  draw_menu
}

# อ่าน 1 keystroke แล้วแปลเป็นชื่อปุ่ม (ลูกศรมาเป็น escape sequence 3 ไบต์: ESC [ A)
#
# bash 3.2 (ตัว default ของ macOS) ไม่รองรับ `read -t` แบบทศนิยม — จะคุม timeout
# ของ escape sequence ด้วย stty `min 0 time 1` (รอไม่เกิน 0.1 วิ แล้วคืนเท่าที่มี)
# เพื่อให้กด Esc เปล่าๆ ไม่ค้างรอปุ่มถัดไป
read_key() {
  local key rest
  IFS= read -rsn1 key 2>/dev/null || return 1
  case "$key" in
    $'\e')
      rest=""
      if [ -n "$STTY_SAVED" ]; then
        stty min 0 time 1 2>/dev/null || true
        IFS= read -rsn2 rest 2>/dev/null || true
        stty min 1 time 0 2>/dev/null || true
      else
        IFS= read -rsn2 -t 1 rest 2>/dev/null || true
      fi
      case "$rest" in
        '[A') printf 'up' ;;
        '[B') printf 'down' ;;
        *)    printf 'esc' ;;
      esac ;;
    '')  printf 'enter' ;;
    ' ') printf 'space' ;;
    *)   printf '%s' "$key" ;;
  esac
}

toggle_at() {
  local i="$1"
  [ "${SEL[$i]}" = 1 ] && SEL[$i]=0 || SEL[$i]=1
}

choose_menu() {
  sel_to_array

  STTY_SAVED="$(stty -g 2>/dev/null || true)"
  trap restore_term EXIT INT TERM
  # อ่านทีละปุ่ม ไม่ต้องรอ Enter และไม่ echo ตัวอักษรที่กด
  [ -n "$STTY_SAVED" ] && stty -echo -icanon min 1 time 0 2>/dev/null || true
  printf '\033[?25l'                                   # ซ่อน cursor ระหว่างเลือก

  local key i result=0
  draw_menu
  while :; do
    key="$(read_key)" || { result=1; break; }
    case "$key" in
      up|k)    CURSOR=$(( (CURSOR - 1 + ${#LABELS[@]}) % ${#LABELS[@]} )) ;;
      down|j)  CURSOR=$(( (CURSOR + 1) % ${#LABELS[@]} )) ;;
      space)   toggle_at "$CURSOR" ;;
      a|A)     for i in "${!LABELS[@]}"; do SEL[$i]=1; done ;;
      n|N)     for i in "${!LABELS[@]}"; do SEL[$i]=0; done ;;
      [1-4])   CURSOR=$((key - 1)); toggle_at "$CURSOR" ;;
      enter)   break ;;
      q|Q|esc) result=1; break ;;
    esac
    redraw_menu
  done

  restore_term
  trap - EXIT INT TERM

  if [ "$result" = 1 ]; then
    info "ยกเลิก"
    return 1
  fi

  array_to_sel
  if [ "$SEL_CLAUDE$SEL_CODEX$SEL_AGY$SEL_SHELL" = "0000" ]; then
    warn "ไม่ได้เลือกอะไรเลย — ไม่มีอะไรให้ทำ"
    return 1
  fi
  save_prefs
  return 0
}

run_selected() {
  # install_shared ต้องรันเสมอถ้ามีการติดตั้ง assistant ตัวใดตัวหนึ่ง
  if [ "$SEL_CLAUDE" = 1 ] || [ "$SEL_CODEX" = 1 ] || [ "$SEL_AGY" = 1 ]; then
    install_shared
  fi
  [ "$SEL_CLAUDE" = 1 ] && install_claude
  [ "$SEL_CODEX"  = 1 ] && install_codex
  [ "$SEL_AGY"    = 1 ] && install_antigravity
  [ "$SEL_SHELL"  = 1 ] && install_shell
  return 0
}

summary() {
  head2 "เสร็จแล้ว"
  [ "$SEL_CLAUDE" = 1 ] && info "Claude      → /status, /ai-init"
  [ "$SEL_CODEX"  = 1 ] && info "Codex       → \$status, \$ai-init"
  [ "$SEL_AGY"    = 1 ] && info "Antigravity → เรียกชื่อ skill ได้เลย (agy)"
  [ "$SEL_SHELL"  = 1 ] && info "เปิด terminal ใหม่ หรือ source shell rc ก่อนใช้ wrapper"
  return 0
}

main() {
  [ -d "$SRC" ] || { echo "ไม่พบ $SRC" >&2; exit 1; }
  case "${1:-}" in
    --uninstall) uninstall; return ;;
    --status)    status; return ;;
    claude)      SEL_CLAUDE=1 SEL_CODEX=0 SEL_AGY=0 SEL_SHELL=0 ;;
    codex)       SEL_CLAUDE=0 SEL_CODEX=1 SEL_AGY=0 SEL_SHELL=0 ;;
    antigravity|agy) SEL_CLAUDE=0 SEL_CODEX=0 SEL_AGY=1 SEL_SHELL=0 ;;
    shell)       SEL_CLAUDE=0 SEL_CODEX=0 SEL_AGY=0 SEL_SHELL=1 ;;
    all)         SEL_CLAUDE=1 SEL_CODEX=1 SEL_AGY=1 SEL_SHELL=1 ;;
    "")
      # ไม่ระบุ arg: ใช้ค่าที่เคยเลือกไว้ ถ้าไม่มีก็ auto-detect จาก binary ที่ติดตั้งจริง
      load_prefs || detect_defaults
      if [ -t 0 ] && [ -z "${AI_AGENT_YES:-}" ]; then
        choose_menu || return 0
      else
        info "โหมด non-interactive — ใช้ค่าที่บันทึกไว้/auto-detect"
      fi
      ;;
    *)
      echo "ใช้: $0 [all|claude|codex|antigravity|shell|--status|--uninstall]" >&2
      exit 1
      ;;
  esac

  run_selected
  summary
}

main "$@"
